// すぐに使えるプリセットプロファイル。

import type { Profile } from './types'

export const PRESET_PROFILES: Profile[] = [
  {
    id: 'preset-prefix',
    name: '接頭辞方式（データ識別子）',
    splitMode: 'perBarcode',
    delimiters: [],
    collapseSpaces: false,
    completeWhen: 'allRequired',
    fields: [
      {
        id: 'preset-prefix-part-no',
        label: '品番',
        key: 'part_no',
        source: 'both',
        match: { kind: 'prefix', value: 'P', strip: true, caseSensitive: false },
        transforms: [{ kind: 'trim' }],
        required: true,
      },
      {
        id: 'preset-prefix-quantity',
        label: '数量',
        key: 'quantity',
        source: 'both',
        match: { kind: 'prefix', value: 'Q', strip: true, caseSensitive: false },
        transforms: [{ kind: 'trim' }, { kind: 'toNumber' }],
        required: true,
      },
      {
        id: 'preset-prefix-lot-no',
        label: 'ロット',
        key: 'lot_no',
        source: 'both',
        match: { kind: 'prefix', value: '1T', strip: true, caseSensitive: false },
        transforms: [{ kind: 'trim' }],
        required: false,
      },
      {
        id: 'preset-prefix-supplier',
        label: '仕入先',
        key: 'supplier',
        source: 'both',
        match: { kind: 'prefix', value: 'V', strip: true, caseSensitive: false },
        transforms: [{ kind: 'trim' }],
        required: false,
      },
      {
        id: 'preset-prefix-customer-part-no',
        label: '客先品番',
        key: 'customer_part_no',
        source: 'both',
        match: { kind: 'prefix', value: '30P', strip: true, caseSensitive: false },
        transforms: [{ kind: 'trim' }],
        required: false,
      },
      {
        id: 'preset-prefix-date',
        label: '日付',
        key: 'date',
        source: 'both',
        match: { kind: 'prefix', value: 'D', strip: true, caseSensitive: false },
        transforms: [{ kind: 'trim' }],
        required: false,
      },
    ],
  },
  {
    id: 'preset-space',
    name: 'スペース区切り',
    splitMode: 'splitOne',
    delimiters: [' ', '\t'],
    collapseSpaces: true,
    completeWhen: 'allRequired',
    fields: [
      {
        id: 'preset-space-part-no',
        label: '品番',
        key: 'part_no',
        source: 'both',
        match: { kind: 'index', index: 0 },
        transforms: [{ kind: 'trim' }],
        required: true,
      },
      {
        id: 'preset-space-quantity',
        label: '数量',
        key: 'quantity',
        source: 'both',
        match: { kind: 'index', index: 1 },
        transforms: [{ kind: 'trim' }, { kind: 'toNumber' }],
        required: true,
      },
      {
        id: 'preset-space-lot-no',
        label: 'ロット',
        key: 'lot_no',
        source: 'both',
        match: { kind: 'index', index: 2 },
        transforms: [{ kind: 'trim' }],
        required: false,
      },
    ],
  },
  {
    id: 'preset-raw',
    name: '全文そのまま',
    splitMode: 'perBarcode',
    delimiters: [],
    collapseSpaces: false,
    completeWhen: 'allRequired',
    fields: [
      {
        id: 'preset-raw-content',
        label: '内容',
        key: 'raw',
        source: 'both',
        match: { kind: 'rest' },
        transforms: [{ kind: 'trim' }],
        required: false,
      },
    ],
  },
]
